### ISSUE TITLE
[IMPROVEMENT]: Add keyboard filtering to CLI

### ISSUE THREAD

**Issue by jjfantini** [ljnsn/cz-conventional-gitmoji#125]
The Gitmoji CLI should be able to filter down the choices of the commit by using the keyboard, so typing `f`, would bring all of the `f` types available to commit! This would make usability much better :D

**Comment by ljnsn** [comment]
You're using `cz-cli` and `cz-git` those are different from `commitizen`.

**Comment by ljnsn** [comment]
@jjfantini were you able to check this with `commitizen` only?

**Comment by jjfantini** [comment]
Yeah, I found I could filter with just commitizen installed.

sent from humblWorkshop

---------------------------------------------
⬇️⬇️ TRY OUR DATA TOOLS ⬇️⬇️
📈📊humblfinance.io📊📈

⬇️⬇️ JOIN OUR SMALL COMMUNITY ⬇️⬇️
 📓📖humblblog.com📖📓
---------------------------------------------
⬇️⬇️ CONTACT ⬇️⬇️
📧: ***@***.***
📧: ***@***.***
📱: +1 (307) 278-6561

**Comment by ljnsn** [comment]
This does not work with just commitizen.. see the screencap

![Peek 2024-03-11 19-48](https://github.com/ljnsn/cz-conventional-gitmoji/assets/82611987/879f4001-d44a-4835-b2c9-a3764d035cda)

**Comment by jjfantini** [comment]
hmm that's odd, will check and see what I see to have made that work

**Comment by ljnsn** [comment]
Ok, so I'm going to close this one, feel free to reopen or open another ticket if you do think that it's related to this package.
