### ISSUE TITLE
Add support for chore commit type

### ISSUE THREAD

**Issue by donbignose** [ljnsn/cz-conventional-gitmoji#131]
While chore is not a type in cz, it seems to be used and recommended by [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/).

Would it be possible to add it in the mojis that you use? The pre-commit doesn't work for me with chore type commit.

**Comment by ljnsn** [comment]
Chore sounds like a good one to add, but there is no gitmoji for it. So I think if it's added, it should be opt-in via a config option.

What could be the emoji to become the chore gitmoji?

**Comment by jjfantini** [comment]
the wrench 🔧

**Comment by ljnsn** [comment]
That is already taken by `config`. Any of the [official gitmojis](https://gitmoji.dev/) are already mapped.

**Comment by jjfantini** [comment]
What about ⚒️, I cant find that anywhere

**Comment by jjfantini** [comment]
@donbignose I would recommend using `cz_custommize`along with `cz-conventional-gitmoji`. This allows you to declare custom commit types that are parsed by the  `cz-conventional-gitmoji` engine. You can overwrite any emoji for any type of commit that you'd like

**Comment by jjfantini** [comment]
yeah! i think that is a great idea, would love to have that in the commit parser

**Comment by ljnsn** [comment]
I've added the `chore` type without any config option for now. I had already planned to add options to restrict types to conventional only, as well as some other configuration options, so it makes sense to add that together with an option for gitmoji only types. At the moment I don't have the time to do that though, so now it's already possible to use chore just like any of the other types.
