### ISSUE TITLE
[BUG]: `cz_gitmoji` doesn't support bump

### ISSUE THREAD

**Issue by jjfantini** [ljnsn/cz-conventional-gitmoji#138]
I am trying to use `cz-conventional-gitmoji` in a Github Action, to bump my package version automatically.

I am met with this error: `'cz_gitmoji' rule does not support bump`

Even if I run the command on the CLI with `cz --name cz_gitmoji bump`, I get the same error... `'cz_gitmoji' rule does not support bump`

![Screenshot 2024-03-06 090556](https://github.com/ljnsn/cz-conventional-gitmoji/assets/63276164/39410e11-79dc-4178-b80e-e77feafcfaf8)

**Comment by jjfantini** [comment]
I am using the same workflow in my package as I am in  this [package](https://github.com/jjfantini/gitmoji-test). Please take a look and see the config.

 I am wondering what the error is coming from?

**Comment by ljnsn** [comment]
Hey, I have recently set up another repo using `cz_gitmoji` (like pretty much all of them) and bumping is working fine. The [bump config](https://github.com/ljnsn/coinapi-rest/blob/main/.github/workflows/pythonpackage.yml#L105-L109) is the same as yours apart from the `changelog_increment_filename: body.md`, so I am sure it supports bumping.

The issue must be coming from the combination of using this package with some of the other customizations you're doing in your repo. I haven't really tested much with additional customizations. I'm happy to look into it, if you could provide a **minimal reproducible example**. Please set up the project with `gz_gitmoji` only first, make sure that it works and then add your customizations one by one. When you find the one that causes the issue, remove the other ones and post the config here.

**Comment by jzazo** [comment]
I think the conflicting config property is `major_version_zero = true`. When I comment this line out in my `commitizen` config, `cz bump` works, but not when left uncommented.

**Comment by ljnsn** [comment]
Thanks @jzazo! I'll have a look at what causes the issue with this setting.

**Comment by kenibrewer** [comment]
Just wanted to comment that I've run into this bug as well. Thanks for this great tool @ljnsn !

**Comment by ljnsn** [comment]
Should be fixed in the latest version, could one of you confirm?

**Comment by jzazo** [comment]
I think it's working! I added `major_version_zero = true` and it worked.

**Comment by ljnsn** [comment]
Thanks for checking, I'll close this then :slightly_smiling_face:

**Comment by kenibrewer** [comment]
Thanks a ton!
