### ISSUE TITLE
Question: expanded list of types

### ISSUE THREAD

**Issue by jzazo** [ljnsn/cz-conventional-gitmoji#150]
Hi! Is there any place where to look at the expanded list of types that will be recognized and converted to emojis? Is it an official list of gitmoji? 

Also, what will happen when that expanded list is used for bumping packages with commitizen? Are the different categories assigned to default minor and/or partches?

Thanks.

**Comment by ljnsn** [comment]
Hi, only the emojis come from gitmoji, I've mapped them to types that match. It's a good point, that mapping is currently not documented anywhere. I'll add that somewhere more easily findable, in the meantime you can run `cz commit` or check the code [here](https://github.com/ljnsn/cz-conventional-gitmoji/blob/main/src/shared/spec.py).

These are the bump pattern and bump map used by the plugin:

```python
    bump_pattern = (
        rf"^(BREAKING[\-\ ]CHANGE"
        rf"|{GJ_BOOM}? ?boom"
        rf"|{GJ_FEAT}? ?feat"
        rf"|{GJ_FIX}? ?fix"
        rf"|{GJ_HOTFIX}? ?hotfix"
        rf"|{GJ_REFACTOR}? +refactor"
        rf"|{GJ_PERF}? ?perf)"
        r"(\(.+\))?"  # scope
        r"(!)?"  # breaking
    )

    bump_map = OrderedDict(
        (
            (r"^.+!$", MAJOR),
            (r"^BREAKING[\-\ ]CHANGE", MAJOR),
            (rf"^{GJ_BOOM}? ?boom", MAJOR),
            (rf"^{GJ_FEAT}? ?feat", MINOR),
            (rf"^{GJ_FIX}? ?fix", PATCH),
            (rf"^{GJ_HOTFIX}? ?hotfix", PATCH),
            (rf"^{GJ_REFACTOR}? ?refactor", PATCH),
            (rf"^{GJ_PERF}? ?perf", PATCH),
        )
    )
```

Any other types do not result in bumps by default, but you can overwrite that from your config.

**Comment by jzazo** [comment]
I hadn't realized `cz commit` lists all the types, it's a good source to look.

BTW, I realized there are missing spaces between the emoji and the following types: `db`, `arch`, `types` and `deprecation`.

Thanks!

**Comment by ljnsn** [comment]
@jzazo I've added the mapping to the readme. Could you explain what you mean with the missing space or add a screenshot? All the gitmojis are prepended the same way, so not sure how only some of them would miss a space.

**Comment by jzazo** [comment]
For examle, arch:
![image](https://github.com/user-attachments/assets/9979c1a4-e933-4323-accb-f587f4898965)

db here:
![image](https://github.com/user-attachments/assets/bbdf55ba-cf23-4a2c-a1cf-98aaea19736c)

types and deprecation:
![image](https://github.com/user-attachments/assets/c47293f3-fc8b-451b-bb1a-d72e75cb825e)

**Comment by ljnsn** [comment]
Ah, I see in that overview. Thanks!

**Comment by ljnsn** [comment]
Mm, for me it looks like this, no extra spaces (yes, I have some emojis missing):

![image](https://github.com/user-attachments/assets/16f69b70-3d1a-4c15-b892-b928b13d3175)

It could be due to your font or terminal. Some emojis need more space and I support then then kind of swallow the extra space before the type.

**Comment by jzazo** [comment]
yeah, no big deal. I am using vscode's default terminal and font, so no idea.
Trying now on Windows terminal on WSL I get the following spacing:

![image](https://github.com/user-attachments/assets/4f5347bb-f185-4d08-a3e7-44a903326ed8)

**Comment by ljnsn** [comment]
Looks mostly fine, I guess? :smile: 

Tbh, I don't know how to fix this, what we write is "{emoji} {type}: ..." from there on it's the responsibility of the terminal to properly render it. That said, if anyone has a suggestion for how this could be improved I'd be happy to implement it.
