### ISSUE TITLE
Gitmojify pre-commit hook fails for merge commits that commitizen allows

### ISSUE THREAD

**Issue by kenibrewer** [ljnsn/cz-conventional-gitmoji#166]
When merging changes from a main branch into feature branch as follows:

```
git checkout feature-branch
git merge main
> Auto-merging CHANGELOG.md
> CONFLICT (content): Merge conflict in CHANGELOG.md
> Automatic merge failed; fix conflicts and then commit the result.
git add .
git commit
< close text editor with default "Merge branch 'main' into feature-branch" >
```

This error occurs:
```
gitmojify................................................................Failed
- hook id: conventional-gitmoji
- exit code: 1

Traceback (most recent call last):
  File "/home/vscode/.cache/pre-commit/repo75cf19di/py_env-python3/bin/gitmojify", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/vscode/.cache/pre-commit/repo75cf19di/py_env-python3/lib/python3.11/site-packages/gitmojify/mojify.py", line 57, in run
    f.write(gitmojify(msg))
            ^^^^^^^^^^^^^^
  File "/home/vscode/.cache/pre-commit/repo75cf19di/py_env-python3/lib/python3.11/site-packages/gitmojify/mojify.py", line 42, in gitmojify
    raise ValueError("invalid commit message")
ValueError: invalid commit message
```

This behavior is different from commitizen which includes "Merge" commits in its list of ignored commits. See [docs](https://commitizen-tools.github.io/commitizen/config/#allowed_prefixes). 

One possible solution would be fetching the set of allowed commits messages from the commitizen configuration and allowing them. That seems pretty complicated though. 

The approach that seems both a bit easier to implement and potentially more on theme with `gitmojify` would be automatically correct these non-conventional commits into gitmojified commits. The one downside to that approach is that would potentially mean that these low-information commits might get added to the changelog when previously they weren't.

**Comment by ljnsn** [comment]
Mmm interesting, the `allowed_prefixes` are the default ones, but they are indeed not even read by gitmojify. I usually set up gitlab/github to use a gitmojified commit message for merges and I rarely ever merge locally, so haven't come across this.

> One possible solution would be fetching the set of allowed commits messages from the commitizen configuration and allowing them.

I think this is what should happen. At some point this package should provide some configuration options too, so then we would need to hook into the commitizen config in any case.

> The approach that seems both a bit easier to implement and potentially more on theme with gitmojify would be automatically correct these non-conventional commits into gitmojified commits.

I'm not a huge fan of that tbh, right now gitmojify just adds the corresponding emoji and doesn't alter the message in any other way, auto converting the message itself to be conventional compliant is not really in scope for this lib.

When I find some time I'll look into your first suggestion. In the meantime, PRs are always welcome! :)

**Comment by gbaian10** [comment]
I have the same issue.
When merging locally, the merge message generated by Git automatically causes this problem.
I hope for a feature like `allowed_prefixes`.

**Comment by ljnsn** [comment]
@kenibrewer I thought about your suggestion again and I do think it makes sense to convert the message in some cases. There seems to be no way to provide a template for those automatic messages locally, so the only way is some external script. Makes more sense to just use gitmojify in that case imo.

I've now implemented `allowed_prefixes`, they can be passed as an argument to `gitmojify` itself or will be picked up from the commitizen config (so if not set, they'll be the commitizen default). They work exactly the same as in commitizen, an allowed prefix is not changed and simply passes checks.

In addition to that, I've added another config option `convert_prefixes`. This defaults to `["Merge", "Revert", "Squash"]` and can also be passed either as argument or via config. Any message starting with one of those prefixes will be converted by simply taking the first word, lowercasing it, and adding a `:` (if it isn't there yet). When using the commitizen hook before the gitmojify hook, convert prefixes also need to be in the allowed prefixes.

I'll also add some other features controlled by their own settings soon, not sure whether I'll keep hijacking commitizen's config or make a separate section for gitmojify only.

I'll close this issue, please open a new one if you find any problems (or have suggestions/feature requests).

**Comment by kenibrewer** [comment]
This seems like a great solution. Thanks!
