### ISSUE TITLE
Ruff isort is not enabled

### ISSUE THREAD

**Issue by gbaian10** [ljnsn/cz-conventional-gitmoji#231]
In this repo original `pyproject.toml`, I saw the [ruff isort settings](https://github.com/ljnsn/cz-conventional-gitmoji/blob/6b01786c9eee818606f9949005cee352a357080f/pyproject.toml#L73).
But the project hasn't enabled the I-series checks (pre-commit won't check them either).

![image](https://github.com/user-attachments/assets/b56ca7a9-a898-4635-b788-29ba5646464b)

Could you consider enabling this check?

**Comment by ljnsn** [comment]
Yep, we can enable them.
