### ISSUE TITLE
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 1068: illegal multibyte sequence

### ISSUE THREAD

**Issue by gbaian10** [ljnsn/cz-conventional-gitmoji#233]
```sh
pytest
```

```sh
tests/cz_gitmoji/test_cz_gitmoji.py::test_info FAILED                                                                                                                                         [ 43%]

============================================================================================= FAILURES ============================================================================================= 
____________________________________________________________________________________________ test_info _____________________________________________________________________________________________ 

cz_gitmoji = <cz_gitmoji.main.CommitizenGitmojiCz object at 0x0000022A60476120>

    def test_info(cz_gitmoji: CommitizenGitmojiCz) -> None:
        """Verify the info content."""
>       info = cz_gitmoji.info()

tests\cz_gitmoji\test_cz_gitmoji.py:86:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  

self = <cz_gitmoji.main.CommitizenGitmojiCz object at 0x0000022A60476120>

    def info(self) -> str:
        """Return information about the commit message style."""
        dir_path = Path(__file__).parent
        # TODO: improve the info file
        filepath = dir_path.joinpath("conventional_gitmojis_info.txt")
        with open(filepath, "r") as f:
>           content = f.read()
E           UnicodeDecodeError: 'cp950' codec can't decode byte 0xe2 in position 1068: illegal multibyte sequence
```

https://github.com/ljnsn/cz-conventional-gitmoji/blob/b26afbedfb3aa381da02c40bc30c6400c7927110/src/cz_gitmoji/main.py#L322

It seems that line is missing `encoding="utf-8"`.

Actually, I've encountered similar issues not only with pytest but also in other places on Windows.

**Comment by gbaian10** [comment]
By the way, a question unrelated to this issue: Are you considering adding Python 3.13 testing in the CI?

Python 3.13 has been officially released, and since 3.8 has reached the end of its lifecycle, are you considering raising the minimum version to 3.9?

https://devguide.python.org/versions/

**Comment by ljnsn** [comment]
> Actually, I've encountered similar issues not only with pytest but also in other places on Windows.

By other places do you mean other places in the code or when running this in other places (not in tests)?

Regarding your question, yes I'll add 3.13 to the CI. I'm aware that 3.8 is EOL and that there are many improvements in newer versions of Python, especially when it comes to typing :slightly_smiling_face: 3.8 is only EOL since September though, so I want to keep supporting it for a bit. In fact, 3.7 support was only dropped because most dependencies are not supporting it anymore and I would have had to stay on a very old version of commitizen. So at some point 3.8 support is going to be dropped for sure, but not yet.

**Comment by gbaian10** [comment]
> By other places do you mean other places in the code or when running this in other places (not in tests)?

I've also encountered this in pre-commit, but I'm not sure if it's caused by that line.

**Comment by ljnsn** [comment]
Do you still see it now after the latest fix?

**Comment by ljnsn** [comment]
So this error was raised by autoupdate itself or by running pre-commit with the newer version?

**Comment by gbaian10** [comment]
### version information

```
pre-commit version: 4.0.1
git --version: git version 2.45.1.windows.1
sys.version:
    3.12.7 (tags/v3.12.7:0b05ead, Oct  1 2024, 03:06:41) [MSC v.1941 64 bit (AMD64)]
sys.executable: .............\.venv\Scripts\python.exe
os.name: nt
sys.platform: win32
```

### error information

```
An unexpected error has occurred: UnicodeDecodeError: 'cp950' codec can't decode byte 0xe5 in position 137: illegal multibyte sequence
```

```
Traceback (most recent call last):
  File ".............\.venv\Lib\site-packages\pre_commit\error_handler.py", line 73, in error_handler
    yield
  File ".............\.venv\Lib\site-packages\pre_commit\main.py", line 377, in main
    return autoupdate(
           ^^^^^^^^^^^
  File ".............\.venv\Lib\site-packages\pre_commit\commands\autoupdate.py", line 170, in autoupdate
    migrate_config(config_file, quiet=True)
  File ".............\.venv\Lib\site-packages\pre_commit\commands\migrate_config.py", line 116, in migrate_config
    orig_contents = contents = f.read()
                               ^^^^^^^^
UnicodeDecodeError: 'cp950' codec can't decode byte 0xe5 in position 137: illegal multibyte sequence
```

It seems to be an issue caused by pre-commit itself.
Since I rarely use Windows for development, I haven't encountered these problems much in the past.

**Comment by ljnsn** [comment]
Yep, seems like it's a pre-commit issue 👍
